feat(api): Adding Survey Slug to the Survey Submission output
MRC-Epid-it24/intake24 pull request #191
Opened 2023-10-18 03:52 UTC by cheburan

A small change to the survey submission is adding a Survey Slug as a parameter to the output. For the sake of the external modules (a.k.a. intake24-dietician).

2023-10-18 09:33 UTC, lukashroch commented
This will only add it to json response output. I think we should include it as field to data export. Maybe add survey name as well?

2023-10-18 12:38 UTC, lukashroch reviewed
This will only add it to json response output. I think we should include it as field to data export. Maybe add survey name as well?

2023-10-19 00:41 UTC, cheburan commented
@lukashroch Reasonable.  Adding a field object to `data-export-files.ts` will do the trick, as I understand. 

Will do that once I figure out why my data export doesn't work and can't be configured via the admin dashboard.
Have some issues with modifying the data export for the survey schema. I don't think it is connected to the task itself, rather then the survey schema. For some reason, I can't save the changes in the exported fields (admin dashboard) list even if I don't change the code and list of fields. Getting the following error: 
```
ExportSections/3/id must be equal to one of the allowed values. Where 3 is `surveyCustom`. 

Not sure if it is only me, but it is missing the translation in the admin dashboard, too - `survey-schemes.data-export.sections.surveyCustom.`
```
when sending the request to `http://{HOST}api/admin/survey-schemes/8`.

It seems connected to the `surveyCustom` section in the Exported Fields. Similar to the `TypeError: dataExportMapper[section.id] is not a function` error I get when exporting the data. In the `getExportFields` function on the execution of `dataExportMapper[section.id](section.fields)` on the `surveyCustoms` section (API). 

Do you know if surveyCustom was added recently? Do I need to run any migration/code or change the survey schema?

2023-10-19 08:45 UTC, lukashroch commented
It was added couple of months ago. I thought admin screen is merging with default so new section would me merged. We'll probably have to look into that.
If you paste in into raw json
```
[
  { id: 'user', fields: [] },
  { id: 'userCustom', fields: [] },
  { id: 'survey', fields: [] },
  { id: 'submission', fields: [] },
  { id: 'submissionCustom', fields: [] },
  { id: 'meal', fields: [] },
  { id: 'mealCustom', fields: [] },
  { id: 'food', fields: [] },
  { id: 'foodCustom', fields: [] },
  { id: 'foodFields', fields: [] },
  { id: 'foodNutrients', fields: [] },
  { id: 'portionSizes', fields: [] },
]
```

I think that should work?

2023-10-19 23:24 UTC, cheburan commented
> It was added couple of months ago. I thought admin screen is merging with default so new section would be merged. We'll probably have to look into that. If you paste in into raw json
> 
> ```
> [
>   { id: 'user', fields: [] },
>   { id: 'userCustom', fields: [] },
>   { id: 'survey', fields: [] },
>   { id: 'submission', fields: [] },
>   { id: 'submissionCustom', fields: [] },
>   { id: 'meal', fields: [] },
>   { id: 'mealCustom', fields: [] },
>   { id: 'food', fields: [] },
>   { id: 'foodCustom', fields: [] },
>   { id: 'foodFields', fields: [] },
>   { id: 'foodNutrients', fields: [] },
>   { id: 'portionSizes', fields: [] },
> ]
> ```
> 
> I think that should work?

Yep, it all worked. Now, Survey Slug is added as an option for the Survey fields' export 
<img width="866" alt="Screenshot 2023-10-20 at 10 22 27" src="https://github.com/MRC-Epid-it24/intake24/assets/11454021/60440437-faed-46e7-b849-627d2680d1e5">

2023-10-19 23:24 UTC, lukashroch commented
Sorry,  `surveyCustom` actually became `submissionCustom` and `survey` is referencing the survey rather than the `submission`

2023-10-19 23:31 UTC, lukashroch requested changes
Please add it also to docs: https://github.com/MRC-Epid-it24/intake24/blob/master/docs/admin/surveys/schemes.md#survey-record-fields

2023-10-19 23:31 UTC, lukashroch commented on packages/i18n/src/admin/en/survey-schemes.json
> +      "surveyCustom": "Survey custom fields",
Not used anymore, remove please.

2023-10-20 05:06 UTC, cheburan commented
> Please add it also to docs: https://github.com/MRC-Epid-it24/intake24/blob/master/docs/admin/surveys/schemes.md#survey-record-fields

added

2023-10-20 07:55 UTC, merged